spring:
  application:
    name: url_shortener
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3106/url_shortener_prod
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: INFO
    org:
      springdoc: INFO
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true